Repository equinor/fusion-react-components, pull requests merged in 2022-11, with the labels that each got.

#431 Feat/PersonCard
  package-lock.json
  packages/person/CHANGELOG.md
  packages/person/README.md
  packages/person/package.json
  packages/person/src/PersonAvatar.tsx
  packages/person/src/PersonCard.tsx
  packages/person/src/PersonProvider.tsx
  packages/person/src/index.tsx
  packages/person/tsconfig.json
  storybook/package.json
  storybook/src/stories/person/avatar.stories.mdx
  storybook/src/stories/person/avatar.stories.tsx
  storybook/src/stories/person/card.stories.mdx
  storybook/src/stories/person/card.stories.tsx
  storybook/tsconfig.json
  tsconfig.json
Labels: enhancement

#458 fix(person): import latest person version from web components
  packages/person/package.json
Labels: bug, prioritized, dependencies

#470 chore(searchable-dropdown): updating webcomponent to 0.3.2
  packages/searchable-dropdown/package.json
Labels: prioritized, dependencies

#486 fix(searchable-dropown): bumping fwc-searchable-dropdown
  packages/searchable-dropdown/package.json
Labels: dependencies
