Repository equinor/fusion-react-components, pull requests merged in 2023-07, with the labels that each got.

#903 chore(button): update icon button
  packages/button/package.json
  packages/button/src/index.tsx
  storybook/src/stories/button/icon-button-toggle/examples.stories.tsx
  storybook/src/stories/button/icon-button/examples.stories.tsx
Labels: dependencies

#895 fix(markdown-editor): onInput event
  packages/markdown/package.json
  packages/markdown/src/MarkdownEditor.tsx
  storybook/src/stories/markdown/markdown-editor/component.stories.mdx
  storybook/src/stories/markdown/markdown-editor/examples.stories.tsx
Labels: bug

#904 feat(stepper): stepper component
  packages/stepper/CHANGELOG.md
  packages/stepper/README.md
  packages/stepper/package.json
  packages/stepper/src/Step.tsx
  packages/stepper/src/StepContent.tsx
  packages/stepper/src/StepPane.tsx
  packages/stepper/src/Stepper.tsx
  packages/stepper/src/index.tsx
  packages/stepper/src/style.ts
  packages/stepper/tsconfig.json
  storybook/package.json
  storybook/src/stories/stepper/component.stories.mdx
  storybook/src/stories/stepper/component.stories.tsx
  storybook/tsconfig.json
  tsconfig.json
Labels: enhancement, prioritized

#915 Fix/styles/dependency/wc theme
  packages/ag-grid-styles/src/agGridStyles/styles.jss.json
  packages/styles/package.json
Labels: bug, prioritized, dependencies
