Repository equinor/fusion-react-components, pull requests merged in 2023-11, with the labels that each got.

#1104 Feat/stepper/step direction
  .changeset/sharp-roses-remain.md
  packages/stepper/src/Stepper.tsx
  packages/stepper/src/style.ts
  pnpm-lock.yaml
  storybook/src/stories/stepper/component.stories.mdx
  storybook/src/stories/stepper/component.stories.tsx
Labels: enhancement

#1126 Fix/person/select/selectevent
  .changeset/violet-plants-press.md
  packages/ag-grid-styles/src/agGridStyles/styles.jss.json
  packages/person/package.json
  packages/person/src/PersonAvatar.tsx
  packages/person/src/PersonCard.tsx
  packages/person/src/PersonListItem.tsx
  packages/person/src/PersonSelect.tsx
  packages/person/src/index.tsx
  pnpm-lock.yaml
Labels: bug

#1124 Chore/context selector/dropdown/hide dom inactive
  .changeset/loud-peas-type.md
  packages/context-selector/src/ContextSearch.tsx
Labels: bug

#1150 Chore/deps/fwc/searchable dropdown
  .changeset/rare-cats-reply.md
  packages/searchable-dropdown/package.json
  pnpm-lock.yaml
Labels: dependencies
