Repository equinor/fusion-react-components, pull requests merged in 2023-10, with the labels that each got.

#993 build: remove fusion-react-ag-grid-addons
  packages/ag-grid-addons/CHANGELOG.md
  packages/ag-grid-addons/README.md
  packages/ag-grid-addons/package.json
  packages/ag-grid-addons/src/agGridStyles/gulpfile.js
  packages/ag-grid-addons/src/agGridStyles/output/styles.ts
  packages/ag-grid-addons/src/agGridStyles/styles.scss
  packages/ag-grid-addons/src/agGridStyles/useAgGridStyles.ts
  packages/ag-grid-addons/src/changeHandlerUtils/StatusComponent.tsx
  packages/ag-grid-addons/src/changeHandlerUtils/constants.ts
  packages/ag-grid-addons/src/changeHandlerUtils/dataManipulators.ts
  packages/ag-grid-addons/src/changeHandlerUtils/defaultOptions.ts
  packages/ag-grid-addons/src/changeHandlerUtils/index.ts
  packages/ag-grid-addons/src/changeHandlerUtils/types.ts
  packages/ag-grid-addons/src/index.ts
  packages/ag-grid-addons/tsconfig.json
  pnpm-lock.yaml
Labels: dependencies

#1023 feat(avatar): remove avatar
  .changeset/thick-adults-lie.md
  packages/avatar/CHANGELOG.md
  packages/avatar/README.md
  packages/avatar/package.json
  packages/avatar/src/index.tsx
  packages/avatar/tsconfig.json
  pnpm-lock.yaml
  storybook/package.json
  storybook/src/stories/avatar/component.stories.mdx
  storybook/src/stories/avatar/examples.stories.tsx
  storybook/src/stories/avatar/snapshots.stories.mdx
Labels: dependencies

#1042 feat(badge): remove badge
  .changeset/kind-impalas-happen.md
  packages/badge/CHANGELOG.md
  packages/badge/README.md
  packages/badge/package.json
  packages/badge/src/index.tsx
  packages/badge/tsconfig.json
  pnpm-lock.yaml
  storybook/package.json
  storybook/src/stories/badge/component.stories.mdx
  storybook/src/stories/badge/examples.stories.tsx
  storybook/src/stories/badge/snapshots.stories.mdx
Labels: dependencies

#1101 Chore/deps/fwc/searchable dropdown
  .changeset/silent-kiwis-wash.md
  packages/context-selector/package.json
  packages/searchable-dropdown/package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies

#1109 Chore/ag grid styles/ag grid version
  .changeset/purple-humans-cheer.md
  packages/ag-grid-styles/package.json
  pnpm-lock.yaml
Labels: dependencies

#1100 chore: added missing border radius 2px
  .changeset/eight-rats-play.md
  packages/side-sheet/src/components/Indicator.tsx
Labels: bug

#1112 fix(sidesheet): sidesheet header is hidden behind fusion top bar
  .changeset/breezy-ways-doubt.md
  packages/side-sheet/src/components/SideSheetBase.tsx
Labels: bug
