Repository equinor/fusion-react-components, pull requests merged in 2024-01, with the labels that each got.

#1312 Fix/sidesheet/content height
  .changeset/ten-trains-dress.md
  packages/side-sheet/src/components/Content.tsx
Labels: bug

#1393 chore(typescript): updating typescript to 5. and support for node 20
  package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#1396 fix(deps): reverting update of @equinor/eds-icons
  README.md
  package.json
  packages/ag-grid-styles/src/agGridStyles/styles.jss.json
  packages/filter/package.json
  pnpm-lock.yaml
Labels: dependencies

#1381 chore(person-select): bump fusion-wc-person to resolve onSelect
  .changeset/chatty-seas-behave.md
  packages/person/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#1408 fix(list): fixes error when building cromatic on list component
  .changeset/honest-rings-lay.md
  packages/ag-grid-styles/src/agGridStyles/styles.jss.json
  packages/list/package.json
  packages/list/src/components/CheckListItem.tsx
  packages/list/src/components/ListItem.tsx
  packages/list/src/components/RadioListItem.tsx
  pnpm-lock.yaml
Labels: bug, dependencies

#1418 fix(deps): updating eds-icons and eds-core-react
  packages/ag-grid-utils/package.json
  packages/errorboundary/package.json
  packages/filter/package.json
  packages/side-sheet/package.json
  packages/stepper/package.json
  pnpm-lock.yaml
  storybook/package.json
Labels: bug, dependencies
