Repository equinor/fusion-react-components, pull requests merged in 2024-02, with the labels that each got.

#1483 Feat/stepper/styled components and tokens
  .changeset/tricky-tips-sell.md
  packages/stepper/package.json
  packages/stepper/src/Step.tsx
  packages/stepper/src/StepBadge.tsx
  packages/stepper/src/StepPane.tsx
  packages/stepper/src/Stepper.tsx
  packages/stepper/src/StepperContent.tsx
  packages/stepper/src/StepperControls.tsx
  packages/stepper/src/style.ts
  pnpm-lock.yaml
  storybook/src/stories/stepper/component.stories.mdx
  storybook/src/stories/stepper/component.stories.tsx
Labels: enhancement, dependencies

#1484 docs(storybook): story for PersonSelect selectedPerson attribute
  .changeset/thirty-turtles-train.md
  storybook/src/stories/person/resolve-mock/person-resolve-mock.tsx
  storybook/src/stories/person/select-component.stories.mdx
  storybook/src/stories/person/select-example.stories.tsx
Labels: documentation

#1511 chore(person): updating fosion-wc-person
  .changeset/calm-otters-search.md
  packages/person/package.json
  pnpm-lock.yaml
Labels: dependencies

#1535 Storybook support for searching by upn and azureId in personProvider
  .changeset/weak-zoos-visit.md
  storybook/src/stories_v7/person/person-provider.ts
Labels: bug, documentation
